### ISSUE TITLE
E2E testing

### ISSUE THREAD

**Issue by benji011** [20chix/ziplinks#1]
Hi @20chix im interested in writing E2E tests for this repo.

I have experience using [Cypress](https://www.cypress.io/) . 

Is it ok if i assign myself from the Todo list?

**Comment by 20chix** [comment]
Hey that sounds perfect thanks.

Let me know once you submit a pr and I'll review it as soon as I have time 😊

**Comment by benji011** [comment]
@20chix  
Alright thanks!please assign this issue to me just so everyone knows I'm working on it :)

**Comment by 20chix** [comment]
Will do 🙂

**Comment by 20chix** [comment]
Resolved with pr #11
