### ISSUE TITLE
 Road Map

### ISSUE THREAD

**Issue by 20chix** [20chix/ziplinks#16]
Hi,

Just added 3 features in the roadmap, just wondering if you think they will add value into the project?

 Add Stats in a separate tab, example how many views and links clicks the profile had.
 Allow user to choose from different templates when displaying their profile.
 Allow user to re-order their buttons (tricky :))

**Comment by 20chix** [comment]
@benji011  what you think?

**Comment by benji011** [comment]
@20chix Sorry i completely forgot to reply to this! 

> Add Stats in a separate tab, example how many views and links clicks the profile had.

I think this is cool, but i'm wondering how this would work. Do you mean add stats on their Ziplink profile visits or their SNS?

>  Allow user to choose from different templates when displaying their profile.

Like, switch between light & dark mode or something like MySpace had?

**Comment by 20chix** [comment]
> I think this is cool, but i'm wondering how this would work. Do you mean add stats on their Ziplink profile visits or their SNS?

Yeah on their Ziplinks profile we can add another tab "Stats" and add all the statics about their profile. Example, views and button clicks .


> Like, switch between light & dark mode or something like MySpace had?

The dark and light mode is already covered by background and button color. 
At the moment we can see someone links in the format of buttons one on top of each other, I was thinking to provide other options like this https://designmodo.com/wp-content/uploads/2012/01/metro-590x300.png . What you think?
