### ISSUE TITLE
Load credentials via env variables

### ISSUE THREAD

**Issue by benji011** [20chix/ziplinks#9]
Hi @20chix 

I noticed you hard coded your firebase credentials to the settings file. 
While it helps me personally to get the project running it's probably not a good idea to keep this public (security wise).

I'd like to load have a go and load them through environment variables. If you're happy with this idea, please assign this issue to me and i'll work on it!

**Comment by 20chix** [comment]
Hi, thanks for this, I thought I added this file into git ignore. My bad, don't worry about it, I'll sort it out. Thanks for letting me know ☺️

**Comment by 20chix** [comment]
Hey just wanted to say thanks again for the suggestions. I have now changed credentials to Environment variables.

Feel free to use the other credentials(The one you had on the fork) they where for the dev environment :)
